/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Budget */
        post: operations["get_budget_api_budget_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alternatives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Alternatives */
        post: operations["get_alternatives_api_alternatives_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/savings-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Savings Plan */
        post: operations["get_savings_plan_api_savings_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Product Options */
        post: operations["get_product_options_api_product_options_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/price-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Price History */
        get: operations["price_history_api_price_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add To Cart */
        post: operations["add_to_cart_api_cart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Credentials */
        get: operations["list_credentials_api_auth_credentials_get"];
        put?: never;
        /** Save Credential */
        post: operations["save_credential_api_auth_credentials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/credentials/{cred_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Credential */
        delete: operations["delete_credential_api_auth_credentials__cred_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlternativeGroup */
        AlternativeGroup: {
            /** Name */
            name: string;
            product: components["schemas"]["ProductResponse"];
            /** Count */
            count: number;
            /** Stores */
            stores: string[];
        };
        /** AlternativesRequest */
        AlternativesRequest: {
            /** Query */
            query: string;
            /** Stores */
            stores?: string[] | null;
        };
        /** BrandOption */
        BrandOption: {
            /** Name */
            name: string;
            /** Common Count */
            common_count: number;
            /** Total Stores */
            total_stores: number;
            /** Products */
            products: components["schemas"]["ProductResponse"][];
        };
        /** BudgetItem */
        BudgetItem: {
            /** Query */
            query: string;
            product?: components["schemas"]["ProductResponse"] | null;
            /** Alternatives */
            alternatives?: components["schemas"]["ProductResponse"][] | null;
        };
        /** BudgetRequest */
        BudgetRequest: {
            /** Items */
            items: string[];
            /** Stores */
            stores?: string[] | null;
        };
        /** BudgetResponse */
        BudgetResponse: {
            /** Budgets */
            budgets: {
                [key: string]: components["schemas"]["StoreBudget"];
            };
        };
        /** CartCredentials */
        CartCredentials: {
            /** Email */
            email?: string | null;
            /** Password */
            password?: string | null;
            /**
             * Auth Method
             * @default password
             */
            auth_method: string | null;
            /** Token */
            token?: string | null;
        };
        /** CartItem */
        CartItem: {
            /** Query */
            query: string;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
            /** Name */
            name?: string | null;
        };
        /** CartItemResult */
        CartItemResult: {
            /** Query */
            query: string;
            /** Status */
            status: string;
            /** Error */
            error?: string | null;
        };
        /** CartRequest */
        CartRequest: {
            /** Store Name */
            store_name: string;
            credentials: components["schemas"]["CartCredentials"];
            /** Items */
            items: components["schemas"]["CartItem"][];
        };
        /** CartResponse */
        CartResponse: {
            /** Success */
            success: boolean;
            /** Results */
            results: components["schemas"]["CartItemResult"][];
        };
        /** CharacteristicOption */
        CharacteristicOption: {
            /** Unit */
            unit: string;
            /** Brands */
            brands: components["schemas"]["BrandOption"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** PriceHistoryResponse */
        PriceHistoryResponse: {
            /** Store */
            store: string;
            /** Query */
            query: string;
            /** Product Name */
            product_name: string;
            /** Price */
            price: number;
            /** Unit */
            unit: string;
            /** Brand */
            brand: string;
            /** Recorded At */
            recorded_at: string;
        };
        /** ProductOptionsRequest */
        ProductOptionsRequest: {
            /** Query */
            query: string;
            /** Stores */
            stores?: string[] | null;
        };
        /** ProductOptionsResponse */
        ProductOptionsResponse: {
            /** Characteristics */
            characteristics: components["schemas"]["CharacteristicOption"][];
            cheapest?: components["schemas"]["ProductResponse"] | null;
        };
        /** ProductResponse */
        ProductResponse: {
            /** Name */
            name: string;
            /** Price */
            price: number;
            /** Unit */
            unit: string;
            /** Brand */
            brand: string;
            /** Store */
            store: string;
            /** Url */
            url?: string | null;
            /** Details */
            details?: string | null;
            /** Last Updated */
            last_updated?: string | null;
            /** Price Change Pct */
            price_change_pct?: number | null;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** SavingsPlanItem */
        SavingsPlanItem: {
            product: components["schemas"]["ProductResponse"];
            /** Store */
            store: string;
        };
        /** SavingsPlanRequest */
        SavingsPlanRequest: {
            /** Items */
            items: string[];
            /** Stores */
            stores?: string[] | null;
        };
        /** SavingsPlanResponse */
        SavingsPlanResponse: {
            /** Splits */
            splits: {
                [key: string]: components["schemas"]["StoreSplit"];
            };
            /** Grand Total */
            grand_total: number;
            /** Total Saved */
            total_saved: number;
        };
        /** StoreBudget */
        StoreBudget: {
            /** Items */
            items: components["schemas"]["BudgetItem"][];
            /** Total */
            total: number;
            /** Whatsapp Message */
            whatsapp_message: string;
        };
        /** StoreCredentialRequest */
        StoreCredentialRequest: {
            /** Store Name */
            store_name: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** StoreCredentialResponse */
        StoreCredentialResponse: {
            /** Id */
            id: number;
            /** Store Name */
            store_name: string;
            /** Email */
            email: string;
        };
        /** StoreSplit */
        StoreSplit: {
            /** Items */
            items: components["schemas"]["SavingsPlanItem"][];
            /** Subtotal */
            subtotal: number;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_budget_api_budget_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BudgetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alternatives_api_alternatives_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlternativesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlternativeGroup"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_savings_plan_api_savings_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavingsPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_options_api_product_options_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductOptionsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOptionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    price_history_api_price_history_get: {
        parameters: {
            query: {
                store: string;
                query?: string;
                product_name?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceHistoryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_to_cart_api_cart_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_credentials_api_auth_credentials_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreCredentialResponse"][];
                };
            };
        };
    };
    save_credential_api_auth_credentials_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreCredentialRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreCredentialResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_credential_api_auth_credentials__cred_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cred_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
